"""Add posts, reactions, comments

Revision ID: 6ff0160ab230
Revises: bb79c8436234
Create Date: 2025-11-10 17:37:32.892755

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ff0160ab230"
down_revision: Union[str, Sequence[str], None] = "bb79c8436234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_pinned", sa.String(), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    op.create_index(
        "ix_posts_author_id_deleted_at", "posts", ["author_id", "deleted_at"], unique=False
    )
    op.create_index(
        "ix_posts_community_created_at",
        "posts",
        ["community_id", "created_at", "deleted_at"],
        unique=False,
    )
    op.create_index(
        "ix_posts_community_feed",
        "posts",
        ["community_id", "is_pinned", "created_at", "deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix_posts_community_id"), "posts", ["community_id"], unique=False)
    op.create_index(op.f("ix_posts_deleted_at"), "posts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_posts_is_pinned"), "posts", ["is_pinned"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False)
    op.create_index(
        "ix_comments_author_id_deleted_at", "comments", ["author_id", "deleted_at"], unique=False
    )
    op.create_index(op.f("ix_comments_deleted_at"), "comments", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_comments_parent_id"), "comments", ["parent_id"], unique=False)
    op.create_index(
        "ix_comments_parent_id_deleted_at", "comments", ["parent_id", "deleted_at"], unique=False
    )
    op.create_index(
        "ix_comments_post_created_at",
        "comments",
        ["post_id", "created_at", "deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix_comments_post_id"), "comments", ["post_id"], unique=False)
    op.create_table(
        "reactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("reaction_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "post_id", name="uq_reactions_user_post"),
    )
    op.create_index(op.f("ix_reactions_post_id"), "reactions", ["post_id"], unique=False)
    op.create_index(
        "ix_reactions_post_type", "reactions", ["post_id", "reaction_type"], unique=False
    )
    op.create_index(
        op.f("ix_reactions_reaction_type"), "reactions", ["reaction_type"], unique=False
    )
    op.create_index(op.f("ix_reactions_user_id"), "reactions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reactions_user_id"), table_name="reactions")
    op.drop_index(op.f("ix_reactions_reaction_type"), table_name="reactions")
    op.drop_index("ix_reactions_post_type", table_name="reactions")
    op.drop_index(op.f("ix_reactions_post_id"), table_name="reactions")
    op.drop_table("reactions")
    op.drop_index(op.f("ix_comments_post_id"), table_name="comments")
    op.drop_index("ix_comments_post_created_at", table_name="comments")
    op.drop_index("ix_comments_parent_id_deleted_at", table_name="comments")
    op.drop_index(op.f("ix_comments_parent_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_deleted_at"), table_name="comments")
    op.drop_index("ix_comments_author_id_deleted_at", table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_posts_is_pinned"), table_name="posts")
    op.drop_index(op.f("ix_posts_deleted_at"), table_name="posts")
    op.drop_index(op.f("ix_posts_community_id"), table_name="posts")
    op.drop_index("ix_posts_community_feed", table_name="posts")
    op.drop_index("ix_posts_community_created_at", table_name="posts")
    op.drop_index("ix_posts_author_id_deleted_at", table_name="posts")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
