"""Add events and registrations

Revision ID: a4905d651abd
Revises: ebd7b4c4c70b
Create Date: 2025-11-11 07:01:11.642368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4905d651abd"
down_revision: Union[str, Sequence[str], None] = "ebd7b4c4c70b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("participant_limit", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("end_time > start_time", name="ck_events_valid_time_range"),
        sa.CheckConstraint(
            "participant_limit IS NULL OR participant_limit > 0",
            name="ck_events_positive_participant_limit",
        ),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_community_id"), "events", ["community_id"], unique=False)
    op.create_index(
        "ix_events_community_start_time", "events", ["community_id", "start_time"], unique=False
    )
    op.create_index(op.f("ix_events_creator_id"), "events", ["creator_id"], unique=False)
    op.create_index(op.f("ix_events_start_time"), "events", ["start_time"], unique=False)
    op.create_index(op.f("ix_events_status"), "events", ["status"], unique=False)
    op.create_index("ix_events_status_start_time", "events", ["status", "start_time"], unique=False)
    op.create_table(
        "event_registrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", name="uq_event_registrations_event_user"),
    )
    op.create_index(
        op.f("ix_event_registrations_event_id"), "event_registrations", ["event_id"], unique=False
    )
    op.create_index(
        "ix_event_registrations_event_registered_at",
        "event_registrations",
        ["event_id", "registered_at"],
        unique=False,
    )
    op.create_index(
        "ix_event_registrations_event_status",
        "event_registrations",
        ["event_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_registrations_status"), "event_registrations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_event_registrations_user_id"), "event_registrations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_registrations_user_id"), table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_status"), table_name="event_registrations")
    op.drop_index("ix_event_registrations_event_status", table_name="event_registrations")
    op.drop_index("ix_event_registrations_event_registered_at", table_name="event_registrations")
    op.drop_index(op.f("ix_event_registrations_event_id"), table_name="event_registrations")
    op.drop_table("event_registrations")
    op.drop_index("ix_events_status_start_time", table_name="events")
    op.drop_index(op.f("ix_events_status"), table_name="events")
    op.drop_index(op.f("ix_events_start_time"), table_name="events")
    op.drop_index(op.f("ix_events_creator_id"), table_name="events")
    op.drop_index("ix_events_community_start_time", table_name="events")
    op.drop_index(op.f("ix_events_community_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
