"""Add communities and memberships tables

Revision ID: bb79c8436234
Revises: 72402f0a7778
Create Date: 2025-11-10 11:43:52.311745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb79c8436234"
down_revision: Union[str, Sequence[str], None] = "72402f0a7778"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "communities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("requires_verification", sa.Boolean(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("cover_url", sa.String(), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["communities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_communities_deleted_at"), "communities", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_communities_name"), "communities", ["name"], unique=False)
    op.create_index(
        "ix_communities_name_deleted_at", "communities", ["name", "deleted_at"], unique=False
    )
    op.create_index(op.f("ix_communities_parent_id"), "communities", ["parent_id"], unique=False)
    op.create_index(
        "ix_communities_parent_id_deleted_at",
        "communities",
        ["parent_id", "deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix_communities_type"), "communities", ["type"], unique=False)
    op.create_index(
        "ix_communities_type_deleted_at", "communities", ["type", "deleted_at"], unique=False
    )
    op.create_index(
        "ix_communities_type_visibility_deleted_at",
        "communities",
        ["type", "visibility", "deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix_communities_visibility"), "communities", ["visibility"], unique=False)
    op.create_index(
        "ix_communities_visibility_deleted_at",
        "communities",
        ["visibility", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["community_id"], ["communities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "community_id", name="uq_user_community_membership"),
    )
    op.create_index(
        op.f("ix_memberships_community_id"), "memberships", ["community_id"], unique=False
    )
    op.create_index(
        "ix_memberships_community_id_joined_at",
        "memberships",
        ["community_id", "joined_at"],
        unique=False,
    )
    op.create_index(
        "ix_memberships_community_id_role", "memberships", ["community_id", "role"], unique=False
    )
    op.create_index(op.f("ix_memberships_joined_at"), "memberships", ["joined_at"], unique=False)
    op.create_index(op.f("ix_memberships_role"), "memberships", ["role"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_index("ix_memberships_user_id_role", "memberships", ["user_id", "role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memberships_user_id_role", table_name="memberships")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_role"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_joined_at"), table_name="memberships")
    op.drop_index("ix_memberships_community_id_role", table_name="memberships")
    op.drop_index("ix_memberships_community_id_joined_at", table_name="memberships")
    op.drop_index(op.f("ix_memberships_community_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index("ix_communities_visibility_deleted_at", table_name="communities")
    op.drop_index(op.f("ix_communities_visibility"), table_name="communities")
    op.drop_index("ix_communities_type_visibility_deleted_at", table_name="communities")
    op.drop_index("ix_communities_type_deleted_at", table_name="communities")
    op.drop_index(op.f("ix_communities_type"), table_name="communities")
    op.drop_index("ix_communities_parent_id_deleted_at", table_name="communities")
    op.drop_index(op.f("ix_communities_parent_id"), table_name="communities")
    op.drop_index("ix_communities_name_deleted_at", table_name="communities")
    op.drop_index(op.f("ix_communities_name"), table_name="communities")
    op.drop_index(op.f("ix_communities_deleted_at"), table_name="communities")
    op.drop_table("communities")
    # ### end Alembic commands ###
